version: '3.8'
services:
  db:
    image: postgres:15
    container_name: my-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build: ./backend
    container_name: flask-backend
    depends_on:
      - db
    environment:
      DATABASE_CONNECTION_STRING: "dbname=${POSTGRES_DB} user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} host=db port=5432"
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
    ports:
      - "5000:5000"
    volumes:
      - ./temp/uploads:/app/uploads
  frontend:
    build: ./frontend
    container_name: vite-frontend
    ports:
      - "3000:3000"
    # volumes:
    # - ./frontend:/app
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL}

volumes:
  pgdata:
