version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  mongodb:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  backend:
    build: ./backend
    container_name: flask-backend
    depends_on:
      - db
    environment:
      DATABASE_CONNECTION_STRING: "dbname=${POSTGRES_DB} user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} host=db port=5432"
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
    ports:
      - "5000:5000"
    volumes:
      - ./temp/uploads:/app/uploads
  msg_backend:
    build: ./msg_backend
    container_name: msg-backend
    depends_on:
      - backend
      - mongodb
    environment:
      MONGODB_CONNECTION_STRING: "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/chatdb"
      BACKEND_URL: "http://backend:5000"
    ports:
      - "4350:4350"
  frontend:
    build: ./frontend
    container_name: vite-frontend
    ports:
      - "3000:3000"
    # volumes:
    # - ./frontend:/app
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL}
    profiles: ["tunnel"]

volumes:
  pgdata:
  mongo_data:
